version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: multitenant_db
    environment:
      POSTGRES_DB: multitenant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: multitenant_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: multitenant_api
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SECRET_KEY=django-insecure-change-this-in-production-2025
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web
      - DATABASE_URL=postgres://postgres:postgres@db:5432/multitenant_db
      - REDIS_URL=redis://redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000
      - LOG_LEVEL=INFO

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: 