# Generated by Django 4.2.7 on 2025-06-27 19:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (used for soft delete)",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of the user who created this record",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of the user who last updated this record",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique username for the user",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="User's first name", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(help_text="User's last name", max_length=50),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="User's phone number (optional)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("user", "User"),
                            ("viewer", "Viewer"),
                        ],
                        default="user",
                        help_text="User's role in the system",
                        max_length=10,
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        help_text="Center this user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="centers.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("username",), name="unique_username"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
